/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package js.proyecto.caja;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        operadores = new javax.swing.JLabel();
        caja = new javax.swing.JLabel();
        comisiones = new javax.swing.JLabel();
        gastos = new javax.swing.JLabel();
        patrimonio = new javax.swing.JLabel();
        ajustes = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        operadoresjpanel = new javax.swing.JPanel();
        RECARGAS = new javax.swing.JLabel();
        RETIROS = new javax.swing.JLabel();
        ROPERADORES = new javax.swing.JLabel();
        cajajpanel = new javax.swing.JPanel();
        balance = new javax.swing.JLabel();
        cupoperadores = new javax.swing.JLabel();
        cajatext = new javax.swing.JLabel();
        comisionesjpanel = new javax.swing.JPanel();
        comisiontext = new javax.swing.JLabel();
        comisionPtext = new javax.swing.JLabel();
        gastosjpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        patrimoniojpanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ajustesjpanel = new javax.swing.JPanel();
        agregarope = new javax.swing.JLabel();
        agregarcasa = new javax.swing.JLabel();
        agregarplat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(50, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN");
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 70, 70));

        usuario.setForeground(new java.awt.Color(255, 255, 255));
        usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usuario.setText("USUARIO");
        jPanel2.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 140, 30));

        operadores.setForeground(new java.awt.Color(255, 255, 255));
        operadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        operadores.setText("OPERADORES");
        operadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                operadoresMouseClicked(evt);
            }
        });
        jPanel2.add(operadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 40));

        caja.setForeground(new java.awt.Color(255, 255, 255));
        caja.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caja.setText("CAJA");
        caja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cajaMouseClicked(evt);
            }
        });
        jPanel2.add(caja, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 220, 40));

        comisiones.setForeground(new java.awt.Color(255, 255, 255));
        comisiones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comisiones.setText("COMISIONES");
        comisiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comisionesMouseClicked(evt);
            }
        });
        jPanel2.add(comisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 40));

        gastos.setForeground(new java.awt.Color(255, 255, 255));
        gastos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gastos.setText("GASTOS");
        gastos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gastosMouseClicked(evt);
            }
        });
        jPanel2.add(gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, 40));

        patrimonio.setForeground(new java.awt.Color(255, 255, 255));
        patrimonio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patrimonio.setText("PATRIMONIO");
        patrimonio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patrimonioMouseClicked(evt);
            }
        });
        jPanel2.add(patrimonio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 220, 40));

        ajustes.setForeground(new java.awt.Color(255, 255, 255));
        ajustes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ajustes.setText("AJUSTES");
        ajustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajustesMouseClicked(evt);
            }
        });
        jPanel2.add(ajustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 620));

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 600, 50));

        jPanel6.setLayout(new java.awt.CardLayout());

        operadoresjpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RECARGAS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RECARGAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Recargas{.png"))); // NOI18N
        RECARGAS.setText("RECARGAS");
        operadoresjpanel.add(RECARGAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 220, 110));

        RETIROS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RETIROS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/retiros.png"))); // NOI18N
        RETIROS.setText("RETIROS");
        operadoresjpanel.add(RETIROS, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 230, 120));

        ROPERADORES.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ROPERADORES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/operadores.png"))); // NOI18N
        ROPERADORES.setText("R-OPERADORES");
        operadoresjpanel.add(ROPERADORES, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 250, 110));

        jPanel6.add(operadoresjpanel, "card2");

        balance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/balance.png"))); // NOI18N
        balance.setText(" BALANCE");

        cupoperadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cupooperadores (1).png"))); // NOI18N
        cupoperadores.setText("CUPO OPERADORES");

        cajatext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja.png"))); // NOI18N
        cajatext.setText("CAJA");

        javax.swing.GroupLayout cajajpanelLayout = new javax.swing.GroupLayout(cajajpanel);
        cajajpanel.setLayout(cajajpanelLayout);
        cajajpanelLayout.setHorizontalGroup(
            cajajpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajajpanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(cupoperadores)
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cajajpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cajatext, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
        );
        cajajpanelLayout.setVerticalGroup(
            cajajpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cajajpanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(cajajpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cupoperadores, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(cajatext, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );

        jPanel6.add(cajajpanel, "card3");

        comisiontext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comision.png"))); // NOI18N
        comisiontext.setText("COMISION");

        comisionPtext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/comision-_.png"))); // NOI18N
        comisionPtext.setText("COMISION %");

        javax.swing.GroupLayout comisionesjpanelLayout = new javax.swing.GroupLayout(comisionesjpanel);
        comisionesjpanel.setLayout(comisionesjpanelLayout);
        comisionesjpanelLayout.setHorizontalGroup(
            comisionesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comisionesjpanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(comisiontext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(comisionPtext, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        comisionesjpanelLayout.setVerticalGroup(
            comisionesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(comisionesjpanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(comisionesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comisionPtext)
                    .addComponent(comisiontext))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jPanel6.add(comisionesjpanel, "card4");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gastos.png"))); // NOI18N
        jLabel2.setText("GASTOS MENSUALES");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gastos mensuales.png"))); // NOI18N
        jLabel4.setText("GASTOS UNICOS");

        javax.swing.GroupLayout gastosjpanelLayout = new javax.swing.GroupLayout(gastosjpanel);
        gastosjpanel.setLayout(gastosjpanelLayout);
        gastosjpanelLayout.setHorizontalGroup(
            gastosjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gastosjpanelLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(gastosjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        gastosjpanelLayout.setVerticalGroup(
            gastosjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gastosjpanelLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel4)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        jPanel6.add(gastosjpanel, "card5");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patrimonio.png"))); // NOI18N
        jLabel5.setText("APORTES");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/patrimonio-2.png"))); // NOI18N
        jLabel6.setText("MATERIA PRIMA");

        javax.swing.GroupLayout patrimoniojpanelLayout = new javax.swing.GroupLayout(patrimoniojpanel);
        patrimoniojpanel.setLayout(patrimoniojpanelLayout);
        patrimoniojpanelLayout.setHorizontalGroup(
            patrimoniojpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrimoniojpanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        patrimoniojpanelLayout.setVerticalGroup(
            patrimoniojpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(patrimoniojpanelLayout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addGroup(patrimoniojpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(272, Short.MAX_VALUE))
        );

        jPanel6.add(patrimoniojpanel, "card6");

        agregarope.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar usuario (1).png"))); // NOI18N
        agregarope.setText("AGREGAR OPERADORES");

        agregarcasa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar casa.png"))); // NOI18N
        agregarcasa.setText("AGREGAR CASA");

        agregarplat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar plataforma.png"))); // NOI18N
        agregarplat.setText("AGREGAR PLATAFORMA");

        javax.swing.GroupLayout ajustesjpanelLayout = new javax.swing.GroupLayout(ajustesjpanel);
        ajustesjpanel.setLayout(ajustesjpanelLayout);
        ajustesjpanelLayout.setHorizontalGroup(
            ajustesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajustesjpanelLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addGroup(ajustesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarplat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ajustesjpanelLayout.createSequentialGroup()
                        .addGroup(ajustesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarope, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(213, Short.MAX_VALUE))))
        );
        ajustesjpanelLayout.setVerticalGroup(
            ajustesjpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ajustesjpanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(agregarope)
                .addGap(57, 57, 57)
                .addComponent(agregarcasa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(agregarplat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel6.add(ajustesjpanel, "card7");

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 600, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void operadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_operadoresMouseClicked
        operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(true);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(false);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(false);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(false);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(false);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(false);
    }//GEN-LAST:event_operadoresMouseClicked

    private void cajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cajaMouseClicked
         operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(false);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(true);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(false);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(false);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(false);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(false);
    }//GEN-LAST:event_cajaMouseClicked

    private void comisionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comisionesMouseClicked
        operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(false);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(false);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(true);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(false);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(false);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(false);
    }//GEN-LAST:event_comisionesMouseClicked

    private void gastosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gastosMouseClicked
       operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(false);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(false);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(false);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(true);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(false);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(false);
    }//GEN-LAST:event_gastosMouseClicked

    private void patrimonioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patrimonioMouseClicked
         operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(false);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(false);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(false);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(false);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(true);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(false);
    }//GEN-LAST:event_patrimonioMouseClicked

    private void ajustesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajustesMouseClicked
       operadores.setBackground(Color.red);
        operadoresjpanel.setVisible(false);
        
        caja.setBackground(Color.red);
        cajajpanel.setVisible(false);
        
        comisiones.setBackground(Color.red);
        comisionesjpanel.setVisible(false);
        
        gastos.setBackground(Color.red);
        gastosjpanel.setVisible(false);
        
        patrimonio.setBackground(Color.red);
        patrimoniojpanel.setVisible(false);
        
        ajustes.setBackground(Color.red);
        ajustesjpanel.setVisible(true);
    }//GEN-LAST:event_ajustesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RECARGAS;
    private javax.swing.JLabel RETIROS;
    private javax.swing.JLabel ROPERADORES;
    private javax.swing.JLabel agregarcasa;
    private javax.swing.JLabel agregarope;
    private javax.swing.JLabel agregarplat;
    private javax.swing.JLabel ajustes;
    private javax.swing.JPanel ajustesjpanel;
    private javax.swing.JLabel balance;
    private javax.swing.JLabel caja;
    private javax.swing.JPanel cajajpanel;
    private javax.swing.JLabel cajatext;
    private javax.swing.JLabel comisionPtext;
    private javax.swing.JLabel comisiones;
    private javax.swing.JPanel comisionesjpanel;
    private javax.swing.JLabel comisiontext;
    private javax.swing.JLabel cupoperadores;
    private javax.swing.JLabel gastos;
    private javax.swing.JPanel gastosjpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel operadores;
    private javax.swing.JPanel operadoresjpanel;
    private javax.swing.JLabel patrimonio;
    private javax.swing.JPanel patrimoniojpanel;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
